# Generated by Django 5.0.6 on 2024-06-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='school',
        ),
    ]
