# Generated by Django 5.0.6 on 2024-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_author_alter_member_city_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('edition', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('book_class', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
