# Generated by Django 5.0.6 on 2024-08-20 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
